language: node_js
node_js:
  - "10.13.0"
services:
  - mongodb
install:
  - npm i
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"",roles:["readWrite"]}); sleep 15;'
script:
  - npm test
notification:
  email: false
