language: node_js
node_js:
  - "10.13.0"
services:
  - mongodb
install:
  - npm i
before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
notification:
  email: false
